pipeline:
  name: anshul-testpipeline
  identifier: anshultestpipeline
  projectIdentifier: anshul_teststo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.anshulgithub
        repoName: dvpwa
        build: <+input>
  stages:
    - stage:
        name: anshul_stage
        identifier: anshul_stage
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Bandit
                      name: Bandit_1
                      identifier: Bandit_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: debug
                          fail_on_severity: none
                  - step:
                      type: Semgrep
                      name: Semgrep_1
                      identifier: Semgrep_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
