pipeline:
  name: anshul-testpipeline
  identifier: anshultestpipeline
  projectIdentifier: anshul_teststo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.anshulgithub
        repoName: dvpwa
        build: <+input>
  stages:
    - stage:
        name: anshul_stage
        identifier: anshul_stage
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Bandit
                  name: Bandit_1
                  identifier: Bandit_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: debug
                      fail_on_severity: none
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: cd
    - stage:
        name: email
        identifier: email
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: anshul@avyka.com
                    cc: ""
                    subject: "STO ALERT: Scan results for <+pipeline.name>"
                    body: |-
                      "STO scan of <+pipeline.name> found the following issues:  <br>
                      Critical : <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.CRITICAL> <br>
                      New Critical : <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.NEW_CRITICAL> <br>
                      High: <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.HIGH> <br>
                      New High: <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.NEW_HIGH> <br>
                      Medium: <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.MEDIUM> <br>
                      New Medium: <+pipeline.stages.anshul_stage.spec.execution.steps.Bandit_1.output.outputVariables.NEW_MEDIUM> <br> 
                      See https://app.harness.io/ng/#/account/avyka-ai-6367/sto/orgs/default/"
        tags: {}
